name: Docker Image CI

on:
  pull_request:
    branches: ['main']
    paths:
      - 'Dockerfile'
      - 'scripts/*'
      - '.github/workflows/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: |
          SHA7=${GITHUB_SHA::7}
          echo $SHA7
          docker build . --file Dockerfile --tag "devops-toolkit-merge:$GITHUB_SHA"

      - name: Verify tool versions
        run: |
          cd scripts
          chmod +x check_version_in_toolkit.sh
          ./check_version_in_toolkit.sh "devops-toolkit-merge:$GITHUB_SHA"
