name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOOLKIT_IMAGE: "devops-toolkit-review:$GITHUB_SHA"
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $TOOLKIT_IMAGE

    - name: Verify tool versions
      run: |
        cd scripts
        chmod +x check_version_in_toolkit.sh
        ./check_version_in_toolkit.sh $TOOLKIT_IMAGE
