name: Docker Image CI

on:
  pull_request:
    branches: ['main']
    paths:
      - 'Dockerfile'
      - 'scripts/*'
      - '.github/workflows/*'
  push:
    branches: ['main']
    paths:
      - 'Dockerfile'
      - 'scripts/*'
      - '.github/workflows/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build . --file Dockerfile --tag "devops-toolkit-merge:$GITHUB_SHA"

      - name: Verify tool versions
        run: |
          cd scripts
          chmod +x check_version_in_toolkit.sh
          ./check_version_in_toolkit.sh "devops-toolkit-merge:$GITHUB_SHA"

      - name: Push Docker Image
        # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          SHA7=${GITHUB_SHA::7}
          docker tag "devops-toolkit-merge:$GITHUB_SHA" "tungbq/devops-toolkit:main-$SHA7"
          docker images
          # docker push "tungbq/devops-toolkit:main-$SHA7"
