name: Update Versions

on:
  schedule:
    - cron: '0 0 * * 1' # Run every Monday at midnight
  workflow_dispatch:
  # Just for test, todo: remove and only run schedule
  pull_request:
    branches: ['main']
jobs:
  update-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r script_requirements.txt  # Assuming you have a requirements.txt file with necessary Python dependencies
  
      - name: Get Latest Version
        run: python3 scripts/check_latest_version.py "./toolkit_info.json"

      - name: Update Version
        run: python3 scripts/update_latest_version.py "./toolkit_info.json" "./Dockerfile" "./README.md"

      - name: Commit and Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git status
          git add .
          git commit -m "Update versions"
          # git push origin HEAD

      # - name: Open Pull Request
      #   uses: peter-evans/create-pull-request@v6
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: update-versions
      #     title: Update versions
      #     labels: auto-update
      #     body: Automated version update
